blank_issues_enabled: true
contact_links:
  - name: I have a question or need support
    url: https://renesasrulz.com/mcu-mpu/ra/f/forum
    about: The official Renesas support forum for FSP is Renesas Rulz, visit Rulz at www.renesas.com/ra/forum
